services:
  postgres:
    image: postgres:17.4-bookworm
    container_name: horsey-postgres
    # restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    volumes:
      - horsey_pgdata:/var/lib/postgresql/data
      - ./src/main/docker/postgres/:/docker-entrypoint-initdb.d
    networks:
      - horsey-net
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: horsey-keycloak
    depends_on:
      - postgres
    # restart: unless-stopped
    ports:
      - "8081:8080"
    command: ["start-dev", "--import-realm", "-Dkeycloak.profile.feature.upload_scripts=enabled"]
    volumes:
        - ./src/main/docker/keycloak/:/opt/keycloak/data/import/
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://horsey-postgres:5432/horsey_keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    networks:
        - horsey-net



volumes:
  horsey_pgdata:

networks:
  horsey-net:
