services:
  postgres:
    image: postgres:17.4-bookworm
    container_name: horsey-postgres
    # restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_DB: horsey_go_brrrr
    volumes:
      - horsey_pgdata:/var/lib/postgresql/data
    networks:
      - horsey-net


volumes:
  horsey_pgdata:

networks:
  horsey-net:
