quarkus:
  devservices:
    enabled: false # i'm perfectly able to start my own docker containers thank you
  http:
    port: 8080
    root-path: /api
    cors:
      enabled: true
      origins: /.*/

  datasource:
    db-kind: postgresql
    db-version: 17.4
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/horsey_api
  hibernate-orm:
    database:
      generation: drop-and-create
  oidc:
    client-id: horsey-api
    auth-server-url: http://localhost:8081/realms/horsey-realm
    credentials:
      secret: 5P1jLzJpd3mmCBj466BVno257pO3xuk9
    tls:
      verification: none # ✨ security ✨
  keycloak:
    policy-enforcer:
      enable: true


"%prod":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://horsey-postgres:5432/horsey_api